In [1]:
# load sample dataset
import pandas as pd
import seaborn as sns

from ydata_profiling import ProfileReport

df = pd.read_csv('./data/hotel_revenue_edited.csv')
print(df.shape)
df

(141497, 28)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,previous_bookings_not_canceled,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
0,Resort Hotel,1,85,2018,July,27,1,0,3,2,...,0,0,No Deposit,240,0,Transient,82.0,0,1,Canceled
1,Resort Hotel,1,75,2018,July,27,1,0,3,2,...,0,0,No Deposit,15,0,Transient,105.5,0,0,Canceled
2,Resort Hotel,1,23,2018,July,27,1,0,4,2,...,0,0,No Deposit,240,0,Transient,123.0,0,0,Canceled
3,Resort Hotel,1,60,2018,July,27,1,2,5,2,...,0,0,No Deposit,240,0,Transient,107.0,0,2,Canceled
4,Resort Hotel,1,96,2018,July,27,1,2,8,2,...,0,0,No Deposit,No Agent,0,Transient,108.3,0,2,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141492,City Hotel,1,1,2020,February,5,1,0,0,1,...,1,0,No Deposit,No Agent,0,Transient,0.0,0,1,No-Show
141493,City Hotel,1,31,2020,July,29,16,2,0,1,...,2,1,No Deposit,No Agent,0,Transient,135.0,0,2,No-Show
141494,City Hotel,1,25,2020,May,18,6,2,1,1,...,1,0,No Deposit,No Agent,0,Transient,125.0,0,0,No-Show
141495,City Hotel,1,6,2020,July,29,17,1,0,1,...,1,0,No Deposit,No Agent,0,Transient,65.0,0,0,No-Show
141496,City Hotel,1,0,2020,August,31,2,0,2,1,...,0,0,No Deposit,No Agent,0,Transient,65.0,0,1,No-Show

In [2]:
# simple check for nulls
df.isna().sum()[df.isna().sum() > 0]

Series([], dtype: int64)

In [3]:
profile = ProfileReport(df)
# profile.to_notebook_iframe()
profile.to_file('./hotel_rev_edited.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
num_cols = df.select_dtypes(include = 'number').columns
cat_cols = df.select_dtypes(include = 'object').columns

In [5]:
df[cat_cols].describe().T

                       count unique         top    freq
hotel                 141497      2  City Hotel   92673
arrival_date_month    141497     12      August   17714
meal                  141497      4          BB  110929
country               141497    177         PRT   62822
market_segment        141497      7   Online TA   62575
distribution_channel  141497      4       TA/TO  115716
deposit_type          141497      3  No Deposit  122947
agent                 141497    334           9   34069
customer_type         141497      4   Transient  101179
reservation_status    141497      3   Check-Out   88865

In [6]:
df[num_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
is_canceled,141497.0,0.372602,0.483499,0.0,0.0,0.00,1.0,1.0
lead_time,141497.0,102.891206,106.504913,0.0,17.0,68.00,158.0,737.0
arrival_date_year,141497.0,2019.131480,0.651520,2018.0,2019.0,2019.00,2020.0,2020.0
arrival_date_week_number,141497.0,29.043153,13.566284,1.0,18.0,30.00,40.0,52.0
arrival_date_day_of_month,141497.0,15.747118,8.737765,1.0,8.0,16.00,23.0,31.0
stays_in_weekend_nights,141497.0,0.926981,0.997798,0.0,0.0,1.00,2.0,19.0
stays_in_week_nights,141497.0,2.494435,1.900319,0.0,1.0,2.00,3.0,50.0
adults,141497.0,1.858414,0.620834,1.0,2.0,2.00,2.0,55.0
children,141497.0,0.094278,0.380746,0.0,0.0,0.00,0.0,10.0
babies,141497.0,0.008276,0.100506,0.0,0.0,0.00,0.0,10.0
is_repeated_guest,141497.0,0.030997,0.173310,0.0,0.0,0.00,0.0,1.0
previous_cancellations,141497.0,0.125741,1.061252,0.0,0.0,0.00,0.0,26.0
previous_bookings_not_canceled,141497.0,0.120497,1.383577,0.0,0.0,0.00,0.0,72.0
booking_changes,141497.0,0.211354,0.621083,0.0,0.0,0.00,0.0,18.0
days_in_waiting_list,141497.0,2.308275,16.950155,0.0,0.0,0.00,0.0,391.0
adr,141497.0,99.549352,47.542653,0.0,66.0,90.95,123.0,510.0
required_car_parking_spaces,141497.0,0.062263,0.244454,0.0,0.0,0.00,0.0,8.0
total_of_special_requests,141497.0,0.549051,0.786207,0.0,0.0,0.00,1.0,5.0